### ISSUE TITLE
"Instructions" não está funcionando. 

### ISSUE THREAD

**Issue by YuriCirino** [pagseguro/pagbank-for-woocommerce#13]
As instruções contidas no README para instalação na sessão "Instructions" não está funcionando.

> Procure pelo plugin pagbank-for-woocommerce.

Ao procurar com esse nome nada é encontrado. O resultado é o da imagem abaixo.

![image](https://github.com/pagseguro/pagbank-for-woocommerce/assets/48816560/b0671038-7c2e-4542-abeb-7bd50b76fcde)

Ao procurar pelo termo "pag bank" foi encontrado apenas o plugin internacional.
![image](https://github.com/pagseguro/pagbank-for-woocommerce/assets/48816560/0544c093-6060-497e-b507-7166a65a7155)

**Comment by eliasjnior** [comment]
Olá, @YuriCirino.

No momento o nosso plugin ainda está em revisão pela equipe do WordPress.org. Eles estão passando por algumas dificuldades na aprovação dos plugins devido a alta demanda, portanto ainda não temos uma previsão de quando nosso plugin será publicado na loja oficial.

Enquanto isso, você poderá fazer a instalação manual do plugin. Essa instalação manual acompanhará as atualizações quando o plugin for aprovado pela equipe do WordPress.org.

Atualizei a wiki para ficar com as instruções corretas para a instalação manual.

Qualquer dificuldade, fique à vontade para entrar em contato. Obrigado.
