### ISSUE TITLE
Não foi possível ativar o plugin porque ele gerou um erro fatal.

### ISSUE THREAD

**Issue by wisliy** [pagseguro/pagbank-for-woocommerce#15]
Baixei o plugin diretamente deste repositório, mas na hora de ativar aparece esta mensagem:

Não foi possível ativar o plugin porque ele gerou um erro fatal.

`
Fatal error: Uncaught Error: Class 'PagBank_WooCommerce\Presentation\PaymentGatewaysFields' not found in /home/user/public_html/wp-content/plugins/pagbank-for-woocommerce/pagbank-for-woocommerce.php:35 Stack trace: #0 /home/user/public_html/wp-content/plugins/pagbank-for-woocommerce/pagbank-for-woocommerce.php(41): {closure}() #1 /home/user/public_html/wp-admin/includes/plugin.php(2318): include_once('/home/storage/0...') #2 /home/user/public_html/wp-admin/plugins.php(192): plugin_sandbox_scrape('pagbank-for-woo...') #3 {main} thrown in /home/user/public_html/wp-content/plugins/pagbank-for-woocommerce/pagbank-for-woocommerce.php on line 35
`

**Comment by eliasjnior** [comment]
Olá, @wisliy. Você baixou diretamente da [aba releseases](https://github.com/pagseguro/pagbank-for-woocommerce/releases)?

**Comment by wisliy** [comment]
Tinha baixado na tela inicial > Code > Download ZIP. Baixando pela aba releases deu certo.

Obrigado pela atenção.
