### ISSUE TITLE
Aviso de incompatibilidade com o HPOS

### ISSUE THREAD

**Issue by TECHGAMESPI** [pagseguro/pagbank-for-woocommerce#17]
Ao fazer a instalação do plugin para usar com o woocomerce ele apresentou esse asivo onde informa uma incompatibilidade. 
![image](https://github.com/pagseguro/pagbank-for-woocommerce/assets/114101679/11dc2c7b-a8ec-44ee-bdcd-2bbe8e163d40)
Gostaria que dessem uma olhada nele e verificar uma solução

**Comment by TECHGAMESPI** [comment]
A versão do woocomerce 8.2.1
A versão do wordpress é a 6.3.2

**Comment by eliasjnior** [comment]
@TECHGAMESPI ainda não está compatível com uma nova integração do WooCommerce lançado este mês. Para isso você poderá seguir as instruções do seguinte artigo e ativar o modo de compatibilidade: https://woocommerce.com/document/high-performance-order-storage/

Na próxima atualização já traremos suporte para a versão.

**Comment by eliasjnior** [comment]
@TECHGAMESPI  a release v1.0.4 adiciona o suporte.
