### ISSUE TITLE
Não é possível conectar a conta Pagbank

### ISSUE THREAD

**Issue by ghost** [pagseguro/pagbank-for-woocommerce#20]
Dentro de qualquer configuração de método de pagamento: Cartão de crédito, PIX ou boleto bancário, a opção Conta PagBank fica com botão Carregando... na cor cinza, como se estivesse desativado, sem qualquer opção de clique para conexão.

Abaixo do botão desativado Carregando... é exibida a mensagem: Conecte a sua conta PagBank para aceitar pagamentos, porém não existe uma forma de se conectar.

Tentei selecionar as opções do campo Ambiente: testes e produção, porém o erro continua.

Realizei um teste numa loja virtual ativa e em localhost, porém o o erro foi exibido em ambos projetos.

<img width="533" alt="print" src="https://github.com/pagseguro/pagbank-for-woocommerce/assets/151219988/b518ed03-faba-4d38-bf81-a42b2ada5b86">

**Comment by eliasjnior** [comment]
@victortm2 poderia baixar essa versão https://github.com/pagseguro/pagbank-for-woocommerce/releases/download/v1.0.5/pagbank-for-woocommerce-1.0.5.zip e realizar o teste novamente?

**Comment by ghost** [comment]
Olá @eliasjnior foi justamente essa versão que utilizei 1.0.5, porque a versão anterior 1.0.4, os métodos de pagamento do PagSeguro nem eram listados em WooCommerce > Configurações > Pagamentos.

**Comment by eliasjnior** [comment]
@victortm2 ela foi atualizada há alguns minutos. Acredito que você tenha baixado coincidentemente no momento em que estava sendo publicado. Pode baixar novamente e instalar que deverá funcionar normalmente.

**Comment by ghost** [comment]
@eliasjnior eu realizei o download quando ela havia sido publicada há 5 minutos, mas eu vou exclui-la, baixá-la novamente e lhe informo aqui se o problema foi corrigido.

**Comment by eliasjnior** [comment]
@victortm2 ela acabou sendo republicada, porque o primeiro ZIP acabou subindo sem alguns arquivos, então refiz a release. A publicação da release ainda não está completamente automatizada pois estamos aguardando a aprovação do WordPress para publicá-la no repositório oficial. O plugin já está em revisão e o processo será o padrão para atualização provavelmente em até 2 semanas.

**Comment by ghost** [comment]
@eliasjnior O problema foi corrigido. Obrigado.

**Comment by eliasjnior** [comment]
@victortm2 maravilha, qualquer problema é só informar. Os métodos de pagamento estão sendo listados corretamente?

**Comment by ghost** [comment]
@eliasjnior Tudo perfeito! Já habilitei apenas cartão de crédito e PIX conforme o cliente queria. Primeira vez que estou usando em substituição ao plugin do PagSeguro do Claudio Sanchez.

Assim que acabar de configurar irei testar até a conclusão do pedido.

**Comment by eliasjnior** [comment]
@victortm2 fique à vontade para abrir uma issue caso tenha alguma dificuldade. Vou fechar a issue visto que foi corrigido.

**Comment by jarridlima** [comment]
Olá, pessoal.

Estou com o mesmo problema hoje no LOCALHOST. Estou rodando o PagBank for WooCommerce Versão 1.1.0. Já desinstalei e instalei novamente e continua dando o erro Application error: a client-side exception has occurred (see the browser console for more information).

Não fiz o teste em servidor web, apenas no localhost com MAMP (MacOS).

Tentei tanto em Sandbox quanto em Produção. O erro é o esmo.

![image](https://github.com/pagseguro/pagbank-for-woocommerce/assets/8194683/00841f4c-25c3-4bcd-a26e-7fed9b1dc725)

![image](https://github.com/pagseguro/pagbank-for-woocommerce/assets/8194683/1b58cf7a-1688-4ed5-bd0d-484f2665bb86)
