### ISSUE TITLE
PIX "qr_codes":[{"amount":{"value  not numeric, ceil funcion

### ISSUE THREAD

**Issue by lourenzoavelar** [pagseguro/pagbank-for-woocommerce#22]
In same cases when generating a Pix, the following error message appears in the log during checkout: {"error_messages":[{"code":"40002","description":"must be numeric","parameter_name":"qr_codes[0].amount.value"}]}.

At this line, there was no conversion to an integer. In my case, I used the ceil function and resolved the issue.
"qr_codes":[{"amount":{"value":7423.999999999999},"expiration_date":"2023-12-07T05:06:32+00:00"}]

**Comment by eliasjnior** [comment]
@lourenzoavelar can you tell me what's the product's prices in the cart?

**Comment by eliasjnior** [comment]
@lourenzoavelar na versão 1.0.6 esse erro já está resolvido. Segunda-feira já teremos publicado no repositório oficial do WordPress, então você poderá manter as atualizações automáticas nativas.
