### ISSUE TITLE
Pix

### ISSUE THREAD

**Issue by leandrogrupozani** [pagseguro/pagbank-for-woocommerce#24]
Boa tarde, fiz o texto com cartão de crédito: ok;

porém o pix, ele gera o qr code eu faço o pagamento mas não cai na conta lá do pagseguro.

Olhei agora depois de uns 20 minutos na conta em que o pix saiu.. ainda continua como pendente...

**Comment by eliasjnior** [comment]
Olá, @leandrogrupozani.

Peço que entre em contato com o email suporte-pagbank@cycle-dev.com para solucionar o seu problema.

Att.
