### ISSUE TITLE
Campos do cartão de crédito precisam de melhorias

### ISSUE THREAD

**Issue by tiago-sartor** [pagseguro/pagbank-for-woocommerce#25]
Olá, o novo plugin do PagBank parece ser muito bom! Mas notei que existe a necessidade de melhorar ainda mais a apresentação dos campos de cartão de crédito no checkout. Por exemplo:

1) Adicionar classes ou ids individuais nos elementos que não os possuem, para possibilitar customização via CSS (Ex.: Deixar os campos validade e CVV lado a lado no desktop).

2) Label do campo validade: Mudar "MM/YY" para "MM/AAAA" (Faz mais sentido para lojas PT-BR, além de instruir melhor o usuário a inserir o ano com 4 dígitos ao invés de 2, pois atualmente o campo exige ano com 4 dígitos).
2.1) Se possível, por que não implementar de fato no formato MM / AA nas próximas versões?

3) Fornecer _placeholders_ em todos os campos para melhor UI/UX.

ATUAL:
![Captura de tela 2024-02-07 171245](https://github.com/pagseguro/pagbank-for-woocommerce/assets/77335756/c9f996cd-ebf8-4907-87f7-bd590092d28c)

PROPOSTA:
![(MMAAAA) ](https://github.com/pagseguro/pagbank-for-woocommerce/assets/77335756/29f5f7d1-fb84-4af8-a11d-222984f5fe20)

**Comment by eliasjnior** [comment]
@tiago-123 o formulário de preenchimento será otimizado em futuras versões. Temos planos de otimizações ainda maiores, com uma interface mais amigável para o checkout.

Agradecemos as sugestões.
