### ISSUE TITLE
Application error: a client-side exception has occurred (see the browser console for more information)

### ISSUE THREAD

**Issue by jarridlima** [pagseguro/pagbank-for-woocommerce#26]
Olá, pessoal.

Estou com problema no LOCALHOST. Estou rodando o PagBank for WooCommerce Versão 1.1.0. Já desinstalei e instalei novamente e continua dando o erro Application error: a client-side exception has occurred (see the browser console for more information).

Não fiz o teste em servidor web, apenas no localhost com MAMP (MacOS).

Tentei tanto em Sandbox quanto em Produção. O erro é o esmo.

![image](https://github.com/pagseguro/pagbank-for-woocommerce/assets/8194683/00841f4c-25c3-4bcd-a26e-7fed9b1dc725)

![image](https://github.com/pagseguro/pagbank-for-woocommerce/assets/8194683/1b58cf7a-1688-4ed5-bd0d-484f2665bb86)

_Originally posted by @jarridlima in https://github.com/pagseguro/pagbank-for-woocommerce/issues/20#issuecomment-2010513563_

**Comment by eliasjnior** [comment]
@jarridlima acredito que possa ser devido a URL. Tente utilizar algo como `wordpress.localhost` ao invés de somente localhost.
